cryptoshop/viewer/urls.py
from django.urls import path

from .views import FaqView, FaqCreateView, FaqUpdateView, FaqDeleteView, FaqDetailView, \
    AdvertView, AdvertCreateView, AdvertDetailView, AdvertUpdateView, AdvertDeleteView, news, ArticleCreateView, \
    ArticleDetailView, ArticleDeleteView, ArticleUpdateView


urlpatterns = [
    path('news', news, name='news'),
    path('', AdvertView.as_view(), name='advert'),
    path('advert/new', AdvertCreateView.as_view(), name='advert-create'),
    path('advert/<slug:slug>', AdvertDetailView.as_view(), name='advert-detail'),
    path('advert/<slug:slug>/edit', AdvertUpdateView.as_view(), name='advert-update'),
    path('advert/<slug:slug>/delete', AdvertDeleteView.as_view(), name='advert-delete'),
    path('article/new', ArticleCreateView.as_view(), name='article-create'),
    path('article/<slug:slug>', ArticleDetailView.as_view(), name='article-detail'),
    path('article/<slug:slug>/edit', ArticleUpdateView.as_view(), name='article-update'),
    path('article/<slug:slug>/delete', ArticleDeleteView.as_view(), name='article-delete'),
    path('faq', FaqView.as_view(), name='faq'),
    path('faq/new', FaqCreateView.as_view(), name='faq-create'),
    path('faq/<slug:slug>', FaqDetailView.as_view(), name='faq-detail'),
    path('faq/<slug:slug>/edit', FaqUpdateView.as_view(), name='faq-update'),
    path('faq/<slug:slug>/delete', FaqDeleteView.as_view(), name='faq-delete'),
]

cryptoshop/viewer/models.py
from django.utils.text import slugify
from django.db.models import Model, TextField, CharField,SlugField, ImageField
# Create your models here.


#  Model used for the articles with external URLs for images.

class Article(Model):
    title = CharField(max_length=128)
    content = TextField()
    image = ImageField(upload_to='images', blank=True, null=True)
    slug = SlugField(max_length=128, unique=True)


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def str(self):
        return self.title

    @property
    def image_url_safe(self):
        try:
            url = self.image.url

        except:
            url = ''
        return url


# Model Adverts similar to article (Home)

class Advert(Model):
	title = CharField(max_length=128)
	content = TextField()
	image = ImageField(upload_to='images', blank=True, null=True)
	slug = SlugField(max_length=128, unique=True)

	def save(self, *args, **kwargs):
		if not self.slug:
			self.slug = slugify(self.title)
		super().save(*args, **kwargs)

	def __str__(self):
		return self.title

	@property
	def image_url_safe(self):
		try:
			url = self.image.url

		except:
			url = ''
		return url



class FAQ(Model):
	question = CharField(max_length=128)
	answer = TextField()
	slug = SlugField(max_length=128, unique=True)

	def save(self, *args, **kwargs):
		if not self.slug:
			self.slug = slugify(self.question)
		super().save(*args, **kwargs)

cryptoshop/viewer/templates/advert.html
{% extends 'base.html' %}
{% load static %}
{% block title %}

{% endblock %}
{% block content %}

<h2></h2>


    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>

     <div class="carousel-inner">
        {% for advert in adverts %}
            {% if forloop.first %}
                <div class="carousel-item active  ">
            {% else %}
                    <div class="carousel-item  ">
            {% endif %}
               <img class="d-block w-100 h-50" class="h-50 d-inline-block" src="{{ advert.image_url_safe}}">
                       <div class="carousel-caption d-none d-md-block">
                           <h5 class="lobster"  ><a style="color:white" href="{% url 'advert-detail' advert.slug %}">{{advert.title}}</a></h5>
            </div>

            </div>
        {% endfor %}
     </div>

         <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>

  </div>
        <div class="row">
	{% for article in articles %}
            {% if forloop.counter < 4 %}
		<div class="col-lg-4">
			    <a href="{% url 'article-detail' article.slug %}"> <img class="thumbnail" src="{{ article.image_url_safe }}">
			<div class="box-element article">
				<h6 class="lobster" ><strong>{{article.title}}</strong></h6>
				 {{ article.short_description }}
				<a class="btn btn-outline-success" href="{% url 'article-detail' article.slug %}">View </a>

			</div>
        </div>
            {%endif %}
	{% endfor %}
        </div>
	</div>


<br>


{% endblock %}

cryptoshop/viewer/templates/advert_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
<div class="col-lg-4">
    <img class="thumbnail" src="{{ advert.image_url_safe }}"></div></div>
<h1 class="lobster">{{ advert.title }} </h1>
<h3>{{ advert.content }}</h3>
<br>
<br>
{% if perms.viewer.change_advert %}
<a class="btn btn-secondary" href="{% url 'advert-update' advert.slug %}">Update Advert</a>
<a class="btn btn-danger" href="{% url 'advert-delete' advert.slug %}">Delete Advert</a>
{% endif %}
{% endblock %}

cryptoshop/viewer/templates/advert_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
            {{ form.title.errors }}
            <label for="{{ form.title.id_for_label }}">Advert title</label>
            {{ form.title }}
        </div>
        <div class="form-group">
            {{ form.content.errors }}
            <label for="{{ form.content.id_for_label }}">Advert content</label>
            {{ form.content }}
        </div>
        <div class="form-group">
            {{ form.image.errors }}
            <label for="{{ form.image.id_for_label }}">Advert image</label>
            {{ form.image }}
        </div>
        <input type="submit" value="Submit advert" class="btn btn-primary">
    </form>
{% endblock content %}

cryptoshop/viewer/templates/article_delete.html
{% extends 'base.html' %}

{% block title %}
Removing Article
{% endblock %}


{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>
            Are you sure you want to delete article: <b>{{ object.title }}</b>?
        </p>
        <input type="submit" value="Delete" class="btn btn-danger"/>
    </form>


{% endblock %}\

cryptoshop/viewer/templates/article_detail.html
{% extends 'base.html' %}
{% load auth_extras %}
{% block content %}
<div class="row">
<div class="col-lg-4">
    <img class="thumbnail" src="{{ article.image_url_safe }}"></div></div>
<h1 class="lobster">{{ article.title }} </h1>
<h3>{{ article.content }}</h3>
<br>
<br>
{% if request.user|has_group:"staff" %}
<a class="btn btn-secondary" href="{% url 'article-update' article.slug %}">Update Article</a>
<a class="btn btn-danger" href="{% url 'article-delete' article.slug %}">Delete Article</a>
{% endif %}
{% endblock %}

cryptoshop/viewer/templates/article_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
            {{ form.title.errors }}
            <label for="{{ form.title.id_for_label }}">Article title</label>
            {{ form.title }}
        </div>
        <div class="form-group">
            {{ form.content.errors }}
            <label for="{{ form.content.id_for_label }}">Article content</label>
            {{ form.content }}
        </div>
        <div class="form-group">
            {{ form.image.errors }}
            <label for="{{ form.image.id_for_label }}">Article image</label>
            {{ form.image }}
        </div>
        <input type="submit" value="Submit article" class="btn btn-primary">
    </form>
{% endblock content %}

cryptoshop/viewer/templates/base.html
{% load static %}
{% load auth_extras %}
<html {% if LANGAUGE_CODE %}lang="{{LANGUAGE_CODE }}" {% endif %}>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cryptoshop</title>
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'faq.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
            integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
            integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
            crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <style>.lobster {
font-family: 'Lobster', cursive;
}
.mochi {font-family: 'Mochiy Pop P One', sans-serif;}
</style>
    {% block head %}{% endblock %}
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container fixed">
        <a class="navbar-brand" href="/">{% block title %}{% endblock %}</a>
        <button
                class="navbar-toggler" type="button"
                data-toggle="collapse" data-target="#navbarNavAltMarkup"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">

                <a class="nav-item nav-link active" href="{% url 'advert' %}">
                    Home
                </a>

                <a class="nav-item nav-link active" href="{% url 'faq' %}">
                    FAQ
                </a>

                <a class="nav-item nav-link active" href="{% url 'news' %}">
                    News
                </a>

                <a class="nav-item nav-link active" href="{% url 'store' %}">
                    Courses
                </a>

                <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                Premium
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'cryptomarket' %}">Crypto Market</a>
                    <div class="dropdown-divider"></div>

                    {% if request.user|has_group:"admin" or request.user|has_group:"staff" or request.user|has_group:"premium"%}
                <a class="dropdown-item" href="{% url 'prediction' %}">Predictions</a>
                    <div class="dropdown-divider"></div>
                    {% else %}
                    <a class="dropdown-item" href="{% url 'store' %}">Predictions</a>
                    <div class="dropdown-divider"></div>
                    {% endif %}

                {% if request.user|has_group:"admin" or request.user|has_group:"staff" or request.user|has_group:"premium"%}
                <a class="dropdown-item" href="{% url 'investment_strategies' %}">Investment Strategies</a>
                    <div class="dropdown-divider"></div>
                    {% else %}
                    <a class="dropdown-item" href="{% url 'store' %}">Investment Strategies</a>
                    <div class="dropdown-divider"></div>
                    {% endif %}

                {% if request.user|has_group:"admin" or request.user|has_group:"staff" or request.user|has_group:"premium"%}
                <a class="dropdown-item" href="{% url 'breaking_news' %}">Breaking News</a>
                    <div class="dropdown-divider"></div>
                    {% else %}
                    <a class="dropdown-item" href="{% url 'store' %}">Breaking News</a>
                    <div class="dropdown-divider"></div>
                    {% endif %}

                {% if request.user|has_group:"admin" or request.user|has_group:"staff" or request.user|has_group:"premium"%}
                <a class="dropdown-item" href="{% url 'technnical_analysis' %}">Technical Analysis</a>
                    <div class="dropdown-divider"></div>
                    {% else %}
                    <a class="dropdown-item" href="{% url 'store' %}">Technical Analysis</a>
                    <div class="dropdown-divider"></div>
                    {% endif %}

                {% if request.user|has_group:"admin" or request.user|has_group:"staff" or request.user|has_group:"premium"%}
                <a class="dropdown-item" href="{% url 'chat' %}">Chat with Expert</a>
                    <div class="dropdown-divider"></div>
                    {% else %}
                    <a class="dropdown-item" href="{% url 'store' %}">Chat with Expert</a>
                    <div class="dropdown-divider"></div>
                    {% endif %}

                </div>
                </li>

                <a class="nav-item nav-link active" href="{% url 'contact' %}">
                    Contact
                </a>
                <!-- Cart button -->
                <div class="form-inline my-2 my-lg-0">
                <a href="{% url 'cart' %}">
                <img id="cart-icon" src="{% static 'cart.png' %}">
                </a>
                <p id="cart-total">{{cartitems}}</p>
                </div>
                <div class="form-inline my-2 my-lg-0">
                    {% for message in messages %}
                    <p id="messages"><strong>**{{message}}**</strong></p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div class="navbar-nav ml-auto"><strong><p style="color:white">(Online:{{request.user}})</p></strong></div>

<!--    Drop down menu-->
    <div class="navbar-nav ml-auto">
        <div class="nav-item dropdown">
            <div class="btn-group">
            <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            MENU
            </button>
                <div class="dropdown-menu dropdown-menu-right ">
                    {% if user.is_authenticated %}
                <a href="{% url 'logout' %}" class="dropdown-item text-right">Logout</a>
                                    <a class="dropdown-item text-right" href="{% url 'change_password' %}">Change password</a>
                                    <a class="dropdown-item text-right" href="{% url 'reset_password' %}">Reset password</a>
                   <a class="dropdown-item text-right" href="{% url 'controls' %}">Controls</a>
                    {% else %}
                <a href="{% url 'login' %}" class="dropdown-item text-right">Login</a>
                    <a href="{% url 'signup' %}" class="dropdown-item text-right">SignUp</a>
                    {% endif %}
            </div>
            </div>
        </div>
    </div>

</div>
</nav>
<!-- TradingView Widget BEGIN -->
<div class="tradingview-widget-container">
  <div class="tradingview-widget-container__widget"></div>
  <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-ticker-tape.js" async>
  {
  "symbols": [
    {
      "proName": "FOREXCOM:SPXUSD",
      "title": "S&P 500"
    },
    {
      "proName": "FOREXCOM:NSXUSD",
      "title": "US 100"
    },
    {
      "proName": "FX_IDC:EURUSD",
      "title": "EUR/USD"
    },
    {
      "proName": "BITSTAMP:BTCUSD",
      "title": "Bitcoin"
    },
    {
      "proName": "BITSTAMP:ETHUSD",
      "title": "Ethereum"
    }
  ],
  "showSymbolLogo": true,
  "colorTheme": "dark",
  "isTransparent": false,
  "displayMode": "adaptive",
  "locale": "pl"
}
  </script>
</div>
<!-- TradingView Widget END -->
<br>
<div class="container">
        {% block content %}{% endblock %}
</div>
<script type="text/javascript" src="{% static 'cart.js' %}"></script>
<script type="text/javascript">
var user = '{{request.user}}'
function getToken(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
const csrftoken = getToken('csrftoken');
</script>
<script type="text/javascript" src="{% static 'cart2.js' %}"></script>
</body>

</html>

cryptoshop/viewer/templates/faq.html
{% extends 'base.html' %}
{% load auth_extras %}
{% load static %}

{% block content %}
<img src="static/faq.png" class="img-fluid" alt="Responsive image">

 <div class="row">
     <div class="col-sm-8">
         </br>
         {% for faq in faqy %}
        <div id="faq">
            <div class="card">
                {% if request.user|has_group:"staff" %}
                <div class="card-header" id="heading{{ faq.id }}">
                    <div class="btn btn" id="question" data-toggle="collapse" data-target="#collapse{{ faq.id }}" aria-expanded="false"
                        aria-controls="collapseOne">
                        {{ faq.question }}   <a href ="{% url 'faq-detail' faq.slug %}">     &#x2190;</a>
                    </div>
                </div>
                {% else %}
                <div class="card-header" id="heading{{ faq.id }}">
                    <div class="btn btn" id="question" data-toggle="collapse" data-target="#collapse{{ faq.id }}" aria-expanded="false"
                        aria-controls="collapseOne">
                        {{ faq.question }}
                    </div>
                </div>
                {% endif %}
                <div id="collapse{{ faq.id }}" class="collapse " aria-labelledby="heading{{ faq.id }}" data-parent="#faq">
                    <div class="card-body" id="answer">
                <ul>
                    {{ faq.answer }}
                </ul>
                    </div>
                </div>
            </div>
        </div>
         {% endfor %}
         {% if request.user|has_group:"staff" %}
         <a class="btn btn-primary" href="{% url 'faq-create' %}">New Question</a>
         {% endif %}
 </div>
     <div class ="col-sm-4">
         </br>
         <div id="carouselslide" class="carousel slide" data-ride="carousel">
             <div class="carousel-inner">
        {% for advert in adverts %}
            {% if forloop.first %}
                <div class="carousel-item active  ">
            {% else %}
                  <div class="carousel-item  ">
            {% endif %}
                      <h5>{{ advert.title }}</h5>
               <div class="img" style=" float: align; width: 15em; height: 15em;">
                   <a href="{% url 'advert-detail' advert.slug %}"><img class="thumbnail" src="{{ advert.image_url_safe }}"></a>
               </div>
                </div>
        {% endfor %}
            </div>
  </div>
             <div id="carouselslide1" class="carousel slide" data-ride="carousel">
             <div class="carousel-inner">
        {% for advert in adverts %}
            {% if forloop.counter == 2 %}
                <div class="carousel-item active  ">
            {% else %}
                  <div class="carousel-item  ">
            {% endif %}
                      <h5>{{ advert.title }}</h5>
               <div class="img" style=" float: align; width: 15em; height: 15em;">
                   <a href="{% url 'advert-detail' advert.slug %}"><img class="thumbnail" src="{{ advert.image_url_safe }}"></a>
               </div>
                </div>
        {% endfor %}
            </div>
  </div>
<div id="carouselslide2" class="carousel slide" data-ride="carousel">
             <div class="carousel-inner">
        {% for advert in adverts %}
            {% if forloop.counter == 3 %}
                <div class="carousel-item active  ">
            {% else %}
                  <div class="carousel-item  ">
            {% endif %}
                      <h5>{{ advert.title }}</h5>
               <div class="img" style=" float: align; width: 15em; height: 15em;">
                   <a href="{% url 'advert-detail' advert.slug %}"><img class="thumbnail" src="{{ advert.image_url_safe }}"></a>
               </div>
                </div>
        {% endfor %}
            </div>
  </div>

     </div>
             </div>
         </div>
 </div>
 </div>

{% endblock %}

cryptoshop/viewer/templates/faq_delete.html
{% extends 'base.html' %}

{% block title %}
Removing Question
{% endblock %}


{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>
            Are you sure you want to delete question: <b>{{ object.question }}</b>?
        </p>
        <input type="submit" value="Delete" class="btn btn-danger"/>
    </form>


{% endblock %}

cryptoshop/viewer/templates/faq_detail.html
{% extends 'base.html' %}


{% block content %}
    <h1>{{ faq.question }}</h1>
    <p><h3>Answer:</h3> {{ faq.answer }} </p>

{% if perms.viewer.change_faq %}
<a class="btn btn-secondary" href="{% url 'faq-update' faq.slug %}">Update Question</a>
<a class="btn btn-danger" href="{% url 'faq-delete' faq.slug%}">Delete Question</a>
{% endif %}
{% endblock %}

cryptoshop/viewer/templates/faq_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
            {{ form.question.errors }}
            <label for="{{ form.question.id_for_label }}">Question</label>
            {{ form.question }}
        </div>
        <div class="form-group">
            {{ form.answer.errors }}
            <label for="{{ form.answer.id_for_label }}">Answer</label>
            {{ form.answer }}
        </div>
        <input type="submit" value="Submit" class="btn btn-primary">
    </form>
{% endblock content %}

cryptoshop/viewer/templates/faq_new.html
{% extends 'base.html' %}
{% load auth_extras %}
{% load static %}
{% block content %}

<div class="row">

<div class="col-sm-8 accordion_one">
    {% for faq in faqy %}
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-heading" id="heading{{ faq.id }}">
                <h5 class="panel-title">
                    <a data-toggle="collapse" data-target="#collapse{{ faq.id }}"
                       aria-expanded="false" aria-controls="collapseOne" class="collapsed"> {{ faq.question }} </a>
                </h5>
            </div>
            <div id="collapse{{ faq.id }}" class="panel-collapse collapse" aria-expanded="false" aria-labelledby="heading{{ faq.id }}" role="tablist" style="height: 0px;">
                <div class="panel-body">
                    <div class="text-accordion">
                        <p>{{ faq.answer }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
    <div class="col-sm-4 accordion_two">
        <div id="carouselslide" class="carousel slide" data-ride="carousel">
             <div class="carousel-inner">
        {% for advert in adverts %}
            {% if forloop.first %}
                <div class="carousel-item active  ">
            {% else %}
                  <div class="carousel-item  ">
            {% endif %}
                        <div class="img" style=" float: align; width: 15em; height: 15em;">
                   <a href="{% url 'advert-detail' advert.slug %}"><img class="thumbnail2" src="{{ advert.image_url_safe }}"></a>
                        </div>
                </div>
        {% endfor %}
                </div>
             </div>
            </br>
        <div id="carouselslide1" class="carousel slide" data-ride="carousel">
             <div class="carousel-inner">
                 {% for advert in adverts %}
            {% if forloop.counter == 2 %}
                <div class="carousel-item active  ">
            {% else %}
                  <div class="carousel-item  ">
            {% endif %}
               <div class="img" style=" float: align; width: 15em; height: 15em;">
                   <a href="{% url 'advert-detail' advert.slug %}"><img class="thumbnail2" src="{{ advert.image_url_safe }}"></a>
               </div>
                </div>
        {% endfor %}
            </div>
             </div>
            </br>
        <div id="carouselslide2" class="carousel slide" data-ride="carousel">
             <div class="carousel-inner">
        {% for advert in adverts %}
            {% if forloop.counter == 3 %}
                <div class="carousel-item active  ">
            {% else %}
                  <div class="carousel-item  ">
            {% endif %}
               <div class="img" style=" float: align; width: 15em; height: 15em;">
                   <a href="{% url 'advert-detail' advert.slug %}"><img class="thumbnail2" src="{{ advert.image_url_safe }}"></a>
               </div>
                </div>
        {% endfor %}
            </div>
             </div>
        </div>
        </div>
        </br>
        </div>
    </div>
</div>
{% endblock %}

cryptoshop/viewer/templates/store.html
{% extends 'base.html' %}
{% load auth_extras %}
{% load static %}
{% block content %}
<!--Template for courses (e-store), currently with no functionality. I will sort this out soon. Matt-->

<div class="row">
	{% for product in products %}
		<div class="col-lg-4">
			<a href="{% url 'product_detail' product.id %}"><img class="thumbnail" src="{{ product.image_url_safe }}"></a>
			<div class="box-element product">
				<h6><strong>{{product.name}}</strong></h6>
				<hr>

				<button  data-product="{{ product.id }}" data-action="add" class="btn btn-outline-secondary add-btn
				update-cart">Add to Cart</button>
				<a class="btn btn-outline-success" href="{% url 'product_detail' product.id %}">View</a>
				<h4 style="display: inline-block; float: right"><strong>${{product.price|floatformat:2}}</strong></h4>

			</div>
		</div>
	{% endfor %}

	</div>

<br>
{% if request.user|has_group:"staff" %}
	<a class="btn btn-secondary" href="{% url 'product-create' %}?s=year">Create new product!</a>
{% endif %}
{% endblock  %}